"""empty message

Revision ID: 248c171d1949
Revises: 1b1b2857edb5
Create Date: 2022-05-28 12:01:33.730144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '248c171d1949'
down_revision = '1b1b2857edb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), server_default='true', nullable=False))
    op.drop_column('Artist', 'seeking_venues')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_venues', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_column('Artist', 'seeking_venue')
    # ### end Alembic commands ###
