"""empty message

Revision ID: 53379fef5d13
Revises: 7372a16b6aa4
Create Date: 2022-05-27 22:30:36.827142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53379fef5d13'
down_revision = '7372a16b6aa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website_link', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'website_link')
    # ### end Alembic commands ###
