"""empty message

Revision ID: 761a470164a2
Revises: 53379fef5d13
Create Date: 2022-05-28 11:41:00.383484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '761a470164a2'
down_revision = '53379fef5d13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
